version: "3"
services:
  service_a:
    build: ./service_a
    ports:
      - "5001:5000"
  service_b:
    build: ./service_b
    ports:
      - "5002:5000"
    environment:
      - SERVICE_A_URL=http://service_a:5000/ping
